
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'clickhouse_dw'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'clickhouse_dw'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  sales_data_mart:
    # Config indicated by + and applies to all files under models/example/
    staging:
      schema: staging
      materialized: table
      tags: ['staging']

    intermediate:
      schema: intermediate
      materialized: ephemeral
      tags: ['intermediate']

    mart:
      schema: mart
      materialized: table
      tags: ['mart']

seeds:
  raw_sales_data_mart:
    tags: ['seeds']
    +enabled: true

    raw_countries:
      delimiter: ','
      +schema: raw_countries
      description: "."
      +column_types:
        id: Int
        lang_pt_br: String
        lang_pt_br_formatted: String
        lang_en: String
        lang_en_formatted: String
        alpha_2: String
        alpha_3: String
        create_date_ts: DateTime
      columns:
        - name: id
          description: "Unique identifier of the country in the source system."
        - name: lang_pt_br
          description: "Country name in Brazilian Portuguese (pt-BR), unformatted."
        - name: lang_pt_br_formatted
          description: "Country name in Brazilian Portuguese (pt-BR), with formatting applied (e.g., capitalization)."
        - name: lang_en
          description: "Country name in English (en), unformatted."
        - name: lang_en_formatted
          description: "Country name in English (en), with formatting applied (e.g., capitalization)."
        - name: alpha_2
          description: "ISO 3166-1 alpha-2 country code (2-letter format)."
        - name: alpha_3
          description: "ISO 3166-1 alpha-3 country code (3-letter format)."
        - name: create_date_ts
          description: "Timestamp of record creation or ingestion."

    raw_orders:
      delimiter: ','
      +schema: raw_orders
      description: "Orders placed by customers, including shipment details, dates, and shipping method."
      +column_types:
        order_id: Int
        customer_id: String
        employee_id: Int
        order_date: DateTime
        required_date: DateTime
        shipped_date: DateTime
        ship_via: Int
        freight: Float
        ship_name: String
        ship_address: String
        ship_city: String
        ship_region: String
        ship_postal_code: String
        ship_country: String
      columns:
        - name: order_id
          description: "Unique identifier for each order."
        - name: customer_id
          description: "Identifier of the customer who placed the order."
        - name: employee_id
          description: "Identifier of the employee responsible for the order."
        - name: order_date
          description: "Date when the order was placed."
        - name: required_date
          description: "Date by which the customer requested delivery."
        - name: shipped_date
          description: "Date when the order was shipped."
        - name: ship_via
          description: "Shipping method used, typically referring to a shipping company ID."
        - name: freight
          description: "Shipping cost charged for the order."
        - name: ship_name
          description: "Name of the recipient or company to which the order was shipped."
        - name: ship_address
          description: "Street address for delivery."
        - name: ship_city
          description: "City where the order was shipped."
        - name: ship_region
          description: "Region, state, or province where the order was shipped."
        - name: ship_postal_code
          description: "Postal or ZIP code for the delivery address."
        - name: ship_country
          description: "Country to which the order was shipped."

    raw_order_details:
      delimiter: ','
      +schema: raw_order_details
      description: "Line items within each order, including product, pricing, quantity, and discount information."
      +column_types:
        order_id: Int
        product_id: Int
        unit_price: Float
        quantity: Int
        discount: Float
      columns:
        - name: order_id
          description: "Identifier of the order to which this item belongs."
        - name: product_id
          description: "Identifier of the product included in the order."
        - name: unit_price
          description: "Unit price of the product at the time of the order."
        - name: quantity
          description: "Quantity of the product ordered."
        - name: discount
          description: "Discount applied to the product in this order line, expressed as a decimal (e.g., 0.1 for 10%)."

    raw_products:
      delimiter: ','
      +schema: raw_products
      description: "List of products offered by the company, including pricing, stock levels, and supplier/category information."
      +column_types:
        product_id: Int
        product_name: String
        supplier_id: Int
        category_id: Int
        quantity_per_unit: String
        unit_price: Float
        units_in_stock: Int
        units_on_order: Int
        reorder_level: Int
        discontinued: Int
      columns:
        - name: product_id
          description: "Unique identifier for the product."
        - name: product_name
          description: "Name or title of the product."
        - name: supplier_id
          description: "Identifier of the supplier providing the product."
        - name: category_id
          description: "Identifier of the category to which the product belongs."
        - name: quantity_per_unit
          description: "Description of the quantity per unit (e.g., '10 boxes x 20 bags')."
        - name: unit_price
          description: "Selling price per unit of the product."
        - name: units_in_stock
          description: "Current number of units available in stock."
        - name: units_on_order
          description: "Number of units already ordered but not yet received."
        - name: reorder_level
          description: "Threshold at which new stock should be reordered."
        - name: discontinued
          description: "Indicates whether the product is no longer sold (1 = yes, 0 = no)."
