repos:
  - repo: local
    hooks:
      - id: clear-env-passwords
        name: Remove DBT passwords from .envs
        entry: python scripts/clean_env_passwords.py
        language: system
        files: ^\.env\.(dev|hom|prod|development|homologation|production)$
