version: 2

sources:
  - name: sap
    description: "Raw sales data from the company's ERP system."
    quoting:
      database: true
      schema: false
      identifier: true
    database: dw_rep
    loader: clickhouse
    meta:
      owner: "ERP Company"
    tags: ['raw sales data']

    tables:
      - name: raw_countries
        description: "Contains the standardized list of countries used in the data warehouse, including multilingual names (Portuguese and English), ISO codes, and metadata for data lineage. Each record represents a unique country as defined by the source system, with support for formatted and unformatted naming conventions."
        columns:
        - name: id
          description: "Unique identifier of the country in the source system."
        - name: lang_pt_br
          description: "Country name in Brazilian Portuguese (pt-BR), unformatted."
        - name: lang_pt_br_formatted
          description: "Country name in Brazilian Portuguese (pt-BR), with formatting applied (e.g., capitalization)."
        - name: lang_en
          description: "Country name in English (en), unformatted."
        - name: lang_en_formatted
          description: "Country name in English (en), with formatting applied (e.g., capitalization)."
        - name: alpha_2
          description: "ISO 3166-1 alpha-2 country code (2-letter format)."
        - name: alpha_3
          description: "ISO 3166-1 alpha-3 country code (3-letter format)."
          tests:
            - unique
            - not_null
        - name: create_date_ts
          description: "Timestamp of record creation or ingestion."

      - name: raw_orders
        description: "Orders placed by customers, including shipment details, dates, and shipping method."
        columns:
          - name: order_id
            description: "Unique identifier for each order."
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Identifier of the customer who placed the order."
          - name: employee_id
            description: "Identifier of the employee responsible for the order."
          - name: order_date
            description: "Date when the order was placed."
          - name: required_date
            description: "Date by which the customer requested delivery."
          - name: shipped_date
            description: "Date when the order was shipped."
          - name: ship_via
            description: "Shipping method used, typically referring to a shipping company ID."
          - name: freight
            description: "Shipping cost charged for the order."
          - name: ship_name
            description: "Name of the recipient or company to which the order was shipped."
          - name: ship_address
            description: "Street address for delivery."
          - name: ship_city
            description: "City where the order was shipped."
          - name: ship_region
            description: "Region, state, or province where the order was shipped."
          - name: ship_postal_code
            description: "Postal or ZIP code for the delivery address."
          - name: ship_country
            description: "Country to which the order was shipped."

      - name: raw_order_details
        description: "Line items within each order, including product, pricing, quantity, and discount information."
        columns:
        - name: order_id
          description: "Identifier of the order to which this item belongs."
          tests:
            - unique
            - not_null
        - name: product_id
          description: "Identifier of the product included in the order."
        - name: unit_price
          description: "Unit price of the product at the time of the order."
        - name: quantity
          description: "Quantity of the product ordered."
        - name: discount
          description: "Discount applied to the product in this order line, expressed as a decimal (e.g., 0.1 for 10%)."

      - name: raw_products
        description: "List of products offered by the company, including pricing, stock levels, and supplier/category information."
        columns:
        - name: product_id
          description: "Unique identifier for the product."
          tests:
            - unique
            - not_null
        - name: product_name
          description: "Name or title of the product."
        - name: supplier_id
          description: "Identifier of the supplier providing the product."
        - name: category_id
          description: "Identifier of the category to which the product belongs."
        - name: quantity_per_unit
          description: "Description of the quantity per unit (e.g., '10 boxes x 20 bags')."
        - name: unit_price
          description: "Selling price per unit of the product."
        - name: units_in_stock
          description: "Current number of units available in stock."
        - name: units_on_order
          description: "Number of units already ordered but not yet received."
        - name: reorder_level
          description: "Threshold at which new stock should be reordered."
        - name: discontinued
          description: "Indicates whether the product is no longer sold (1 = yes, 0 = no)."

  - name: stg
    description: "Staging sales data from the company's ERP system."
    quoting:
      database: true
      schema: false
      identifier: true
    database: dw_rep
    loader: clickhouse
    meta:
      owner: "ERP Company"
    tags: ['staging sales data']

    tables:
      - name: stg_countries
        description: "Contains the standardized list of countries used in the data warehouse, including multilingual names (Portuguese and English), ISO codes, and metadata for data lineage. Each record represents a unique country as defined by the source system, with support for formatted and unformatted naming conventions."
        columns:
        - name: id
          description: "Unique identifier of the country in the source system."
        - name: lang_pt_br
          description: "Country name in Brazilian Portuguese (pt-BR), unformatted."
        - name: lang_pt_br_formatted
          description: "Country name in Brazilian Portuguese (pt-BR), with formatting applied (e.g., capitalization)."
        - name: lang_en
          description: "Country name in English (en), unformatted."
        - name: lang_en_formatted
          description: "Country name in English (en), with formatting applied (e.g., capitalization)."
        - name: alpha_2
          description: "ISO 3166-1 alpha-2 country code (2-letter format)."
        - name: alpha_3
          description: "ISO 3166-1 alpha-3 country code (3-letter format)."
          tests:
            - unique
            - not_null
        - name: continent
          description: "Continent to which the country belongs, derived from ISO alpha-2 country code."
        - name: create_date_ts
          description: "Timestamp of record creation or ingestion."
